### ISSUE TITLE
On FreeBSD, src/viewer.c:9:10: fatal error: 'argp.h' file not found

### ISSUE THREAD

**Issue by dereckson** [autopawn/3d-ascii-viewer-c#1]
As argp.h is part of GNU libc, currently the code only compiles on Linux as is.

On FreeBSD for example, there is a package called `argp-standalone` for portability, used by Firefox and ffmpeg, which requires:

  * `-I/usr/local/include` (or better `-I$(PREFIX)/include`) to get /usr/local/include/argp.h
  * `-largp` to link against the library

Not sure for the small arguments parsing done that this dependency is worthwhile, as it  creates issues of portability for 4 small and simple options. As is, the Makefile only works on Linux.

On Mac OS X, brew also provides argp-standalone, so I guess it will be the same issue for all other OSes.

**Comment by dereckson** [comment]
So for example, here how to compile it on FreeBSD:

```
diff --git a/Makefile b/Makefile
index 80e5363..387b492 100644
--- a/Makefile
+++ b/Makefile
@@ -1,8 +1,10 @@
 TARGET_EXEC := viewer
 TEMPDIR := tmp

-CC      := gcc
-LDFLAGS := -lm -lncurses
+PREFIX := /usr/local
+CC      := cc
+CPPFLAGS := -I$(PREFIX)/include
+LDFLAGS := -L$(PREFIX)/lib -lm -lncurses -largp
 SRC_DIR := src

 SRCS := $(shell find $(SRC_DIR) -name '*.c')
```

**Comment by autopawn** [comment]
I am considering implementing a limited version of argp, perhaps leaving out the long version of the arguments for simplicity.

**Comment by autopawn** [comment]
I removed the dependency on argp, at the cost of only receiving arguments on a simpler way.
