### ISSUE TITLE
not an issue but ideas / debian package

### ISSUE THREAD

**Issue by alexmyczko** [autopawn/3d-ascii-viewer-c#7]
check this out! https://www.taat.fi/tmdc/ (i like the tmdc 3 invtro, could not find youtube video of it, maybe works in dosbox)

do you know of a huge archive of free to get obj models?

meshlab is great for converting to obj from other formats (like stl)

and... debian package: http://sid.ethz.ch/debian/3d-ascii-viewer-c/

**Comment by autopawn** [comment]
> do you know of a huge archive of free to get obj models?

No, but I got the current ones from opengameart.org. The license of the models we distribute must be respected, in this case they are all CC0 (public domain), but if we include models with other kinds of open licenses, we may need to ship their licenses as well.

> meshlab is great for converting to obj from other formats (like stl)

I haven't tried it, but I use blender to import models and export them as .obj.

 > and... debian package: http://sid.ethz.ch/debian/3d-ascii-viewer-c/
 
 Nice!
